INSERT INTO MY_USER(ID, USERNAME, PASSWORD, ROLES, ENABLED)
VALUES(1, 'dummy1', 'dummy1', 'ROLE_USER', true);


INSERT INTO MY_USER(ID, USERNAME, PASSWORD, ROLES, ENABLED)
VALUES(2, 'dummy2', 'dummy2', 'ROLE_ADMIN,ROLE_USER', true);